/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './newsfeed';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/LocalData';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from 'ionic-angular/components/popover/popover';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from 'ionic-angular/components/toolbar/toolbar';
import * as import15 from 'ionic-angular/components/navbar/navbar';
import * as import16 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from 'ionic-angular/components/button/button';
import * as import19 from 'ionic-angular/components/icon/icon';
import * as import20 from 'ionic-angular/components/content/content';
import * as import21 from 'ionic-angular/components/refresher/refresher';
import * as import22 from 'ionic-angular/components/refresher/refresher-content';
import * as import23 from '@angular/common/src/directives/ng_for';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import30 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import32 from 'ionic-angular/util/keyboard';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from 'ionic-angular/gestures/gesture-controller';
import * as import36 from '../../node_modules/ionic-angular/components/refresher/refresher-content.ngfactory';
import * as import37 from '@angular/core/src/linker/template_ref';
import * as import38 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import39 from '@angular/core/src/security';
import * as import40 from '@angular/common/src/directives/ng_if';
import * as import41 from 'ionic-angular/components/card/card';
import * as import42 from 'ionic-angular/components/grid/grid';
var renderType_Newsfeed_Host:import0.RenderComponentType = (null as any);
class _View_Newsfeed_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Newsfeed_0_4:import3.Newsfeed;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Newsfeed_Host0,renderType_Newsfeed_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Newsfeed0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Newsfeed_0_4 = new import3.Newsfeed(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.LocalData),this.parentInjector.get(import10.AlertController),this.parentInjector.get(import11.PopoverController));
    this._appEl_0.initComponent(this._Newsfeed_0_4,[],compView_0);
    compView_0.create(this._Newsfeed_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Newsfeed) && (0 === requestNodeIndex))) { return this._Newsfeed_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Newsfeed_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_Newsfeed_Host === (null as any))) { (renderType_Newsfeed_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,[],{})); }
  return new _View_Newsfeed_Host0(viewUtils,parentInjector,declarationEl);
}
export const NewsfeedNgFactory:import13.ComponentFactory<import3.Newsfeed> = new import13.ComponentFactory<import3.Newsfeed>('ng-component',viewFactory_Newsfeed_Host0,import3.Newsfeed);
const styles_Newsfeed:any[] = [];
var renderType_Newsfeed:import0.RenderComponentType = (null as any);
class _View_Newsfeed0 extends import1.AppView<import3.Newsfeed> {
  _el_0:any;
  _Header_0_3:import14.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import15.Navbar;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _Toolbar_5_4:import14.Toolbar;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _ToolbarItem_10_3:import16.ToolbarItem;
  _query_Button_10_0:import17.QueryList<any>;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _Button_12_4:import18.Button;
  _text_13:any;
  _el_14:any;
  _Icon_14_3:import19.Icon;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _Content_20_4:import20.Content;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _Refresher_23_3:import21.Refresher;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _RefresherContent_24_4:import22.RefresherContent;
  _text_25:any;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _TemplateRef_27_5:any;
  _NgFor_27_6:import23.NgFor;
  _text_28:any;
  _text_29:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Newsfeed0,renderType_Newsfeed,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import14.Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','laz-purple');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import27.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import15.Navbar(this.parentInjector.get(import28.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),' \n    \n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([this._text_3])
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','newsfeed-toolbar toolbar');
    this.renderer.setElementAttribute(this._el_5,'color','laz-purple');
    this._appEl_5 = new import2.AppElement(5,0,this,this._el_5);
    var compView_5:any = import29.viewFactory_Toolbar0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Toolbar_5_4 = new import14.Toolbar(this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer);
    this._appEl_5.initComponent(this._Toolbar_5_4,[],compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'b',(null as any));
    this.renderer.setElementAttribute(this._el_7,'style','font-size:17px; color:#FFF');
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_10,'end','');
    this._ToolbarItem_10_3 = new import16.ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_10),this.renderer,this._Toolbar_5_4,this.parentInjector.get(import15.Navbar,(null as any)));
    this._query_Button_10_0 = new import17.QueryList<any>();
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'ion-button','');
    this._appEl_12 = new import2.AppElement(12,10,this,this._el_12);
    var compView_12:any = import30.viewFactory_Button0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Button_12_4 = new import18.Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._Button_12_4,[],compView_12);
    this._text_13 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_14,'name','ios-settings');
    this.renderer.setElementAttribute(this._el_14,'role','img');
    this._Icon_14_3 = new import19.Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_14),this.renderer);
    this._text_15 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_12.create(this._Button_12_4,[[].concat([
        this._text_13,
        this._el_14,
        this._text_15
      ]
    )],(null as any));
    this._text_16 = this.renderer.createText(this._el_10,'\n      ',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_5.create(this._Toolbar_5_4,[
      [],
      [],
      [].concat([this._el_10]),
      [].concat([
        this._text_6,
        this._el_7,
        this._text_9,
        this._text_17
      ]
      )
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_20 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_20 = new import2.AppElement(20,(null as any),this,this._el_20);
    var compView_20:any = import31.viewFactory_Content0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Content_20_4 = new import20.Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_20),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import32.Keyboard),this.parentInjector.get(import33.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import34.Tabs,(null as any)));
    this._appEl_20.initComponent(this._Content_20_4,[],compView_20);
    this._text_21 = this.renderer.createText((null as any),' \n    ',(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'ion-refresher',(null as any));
    this._Refresher_23_3 = new import21.Refresher(this._Content_20_4,this.parentInjector.get(import33.NgZone),this.parentInjector.get(import35.GestureController));
    this._el_24 = this.renderer.createElement(this._el_23,'ion-refresher-content',(null as any));
    this.renderer.setElementAttribute(this._el_24,'pullingIcon','arrow-dropdown');
    this.renderer.setElementAttribute(this._el_24,'pullingText','Pull to refresh');
    this.renderer.setElementAttribute(this._el_24,'refreshingText','Refreshing...');
    this._appEl_24 = new import2.AppElement(24,23,this,this._el_24);
    var compView_24:any = import36.viewFactory_RefresherContent0(this.viewUtils,this.injector(24),this._appEl_24);
    this._RefresherContent_24_4 = new import22.RefresherContent(this._Refresher_23_3,this.parentInjector.get(import24.Config));
    this._appEl_24.initComponent(this._RefresherContent_24_4,[],compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_24.create(this._RefresherContent_24_4,[],(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n    \n    ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_27 = new import2.AppElement(27,20,this,this._anchor_27);
    this._TemplateRef_27_5 = new import37.TemplateRef_(this._appEl_27,viewFactory_Newsfeed1);
    this._NgFor_27_6 = new import23.NgFor(this._appEl_27.vcRef,this._TemplateRef_27_5,this.parentInjector.get(import38.IterableDiffers),this.ref);
    this._text_28 = this.renderer.createText((null as any),'\n',(null as any));
    compView_20.create(this._Content_20_4,[
      [],
      [].concat([
        this._text_21,
        this._text_22,
        this._text_26,
        this._appEl_27,
        this._text_28
      ]
      ),
      [].concat([this._el_23])
    ]
    ,(null as any));
    this._text_29 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_23,'ionRefresh',this.eventHandler(this._handle_ionRefresh_23_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    const subscription_0:any = this._Refresher_23_3.ionRefresh.subscribe(this.eventHandler(this._handle_ionRefresh_23_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Navbar_2_4; }
    if (((token === import19.Icon) && (14 === requestNodeIndex))) { return this._Icon_14_3; }
    if (((token === import18.Button) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Button_12_4; }
    if (((token === import16.ToolbarItem) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ToolbarItem_10_3; }
    if (((token === import14.Toolbar) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Toolbar_5_4; }
    if (((token === import14.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Header_0_3; }
    if (((token === import22.RefresherContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._RefresherContent_24_4; }
    if (((token === import21.Refresher) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Refresher_23_3; }
    if (((token === import37.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import23.NgFor) && (27 === requestNodeIndex))) { return this._NgFor_27_6; }
    if (((token === import20.Content) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Content_20_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_0:any = 'laz-purple';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_2_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    changed = false;
    const currVal_3:any = 'laz-purple';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Toolbar_5_4.color = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_5.componentView.markAsCheckOnce(); }
    const currVal_7:any = 'ios-settings';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Icon_14_3.name = currVal_7;
      this._expr_7 = currVal_7;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_20_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Refresher_23_3.ngOnInit(); }
    const currVal_13:any = 'arrow-dropdown';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._RefresherContent_24_4.pullingIcon = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = 'Pull to refresh';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._RefresherContent_24_4.pullingText = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = 'Refreshing...';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._RefresherContent_24_4.refreshingText = currVal_15;
      this._expr_15 = currVal_15;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RefresherContent_24_4.ngOnInit(); }
    changes = (null as any);
    const currVal_17:any = this.context.events;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._NgFor_27_6.ngForOf = currVal_17;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_17,currVal_17);
      this._expr_17 = currVal_17;
    }
    if ((changes !== (null as any))) { this._NgFor_27_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_27_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_10_0.dirty) {
        this._query_Button_10_0.reset([this._Button_12_4]);
        this._ToolbarItem_10_3._buttons = this._query_Button_10_0;
        this._query_Button_10_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_12_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._Toolbar_5_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_5,'statusbar-padding',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',this.context.message,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_8,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._Icon_14_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_14,'hide',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._Content_20_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_20,'statusbar-padding',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_11:any = (this._Refresher_23_3.state !== 'inactive');
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_23,'refresher-active',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._Refresher_23_3._top;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementStyle(this._el_23,'top',((this.viewUtils.sanitizer.sanitize(import39.SecurityContext.STYLE,currVal_12) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import39.SecurityContext.STYLE,currVal_12).toString()));
      this._expr_12 = currVal_12;
    }
    const currVal_16:any = this._RefresherContent_24_4.r.state;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementAttribute(this._el_24,'state',((currVal_16 == (null as any))? (null as any): currVal_16.toString()));
      this._expr_16 = currVal_16;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_14_3.ngOnDestroy();
    this._Refresher_23_3.ngOnDestroy();
    this._Content_20_4.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.presentPopover($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionRefresh_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doRefresh($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Newsfeed0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.Newsfeed> {
  if ((renderType_Newsfeed === (null as any))) { (renderType_Newsfeed = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_Newsfeed,{})); }
  return new _View_Newsfeed0(viewUtils,parentInjector,declarationEl);
}
class _View_Newsfeed1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _TemplateRef_3_5:any;
  _NgIf_3_6:import40.NgIf;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Newsfeed1,renderType_Newsfeed,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_3 = new import2.AppElement(3,0,this,this._anchor_3);
    this._TemplateRef_3_5 = new import37.TemplateRef_(this._appEl_3,viewFactory_Newsfeed2);
    this._NgIf_3_6 = new import40.NgIf(this._appEl_3.vcRef,this._TemplateRef_3_5);
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._anchor_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import40.NgIf) && (3 === requestNodeIndex))) { return this._NgIf_3_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = ((this.parent.context.timeframe == this.context.$implicit.timeframe) && ((this.parent.context.feedType == 'all') || ((this.parent.context.feedType == 'custom') && this.context.$implicit.visible)));
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_3_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Newsfeed1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_Newsfeed1(viewUtils,parentInjector,declarationEl);
}
class _View_Newsfeed2 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import41.Card;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _CardContent_4_3:import41.CardContent;
  _text_5:any;
  _el_6:any;
  _CardTitle_6_3:import41.CardTitle;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import40.NgIf;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _Row_21_3:import42.Row;
  _text_22:any;
  _el_23:any;
  _Col_23_3:import42.Col;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _Button_25_4:import18.Button;
  _text_26:any;
  _el_27:any;
  _Icon_27_3:import19.Icon;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _Col_34_3:import42.Col;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import2.AppElement;
  _Button_36_4:import18.Button;
  _text_37:any;
  _el_38:any;
  _Icon_38_3:import19.Icon;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Newsfeed2,renderType_Newsfeed,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_0,'style','border-style:solid black');
    this._Card_0_3 = new import41.Card(this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'img',(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_4,'style','padding:1.5%');
    this._CardContent_4_3 = new import41.CardContent();
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-card-title',(null as any));
    this.renderer.setElementAttribute(this._el_6,'style','font-size:18px');
    this._CardTitle_6_3 = new import41.CardTitle();
    this._text_7 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'b',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'   \n                ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_4,'p',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_4,'p',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._appEl_18 = new import2.AppElement(18,4,this,this._anchor_18);
    this._TemplateRef_18_5 = new import37.TemplateRef_(this._appEl_18,viewFactory_Newsfeed3);
    this._NgIf_18_6 = new import40.NgIf(this._appEl_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n            \n            ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this._Row_21_3 = new import42.Row();
    this._text_22 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'ion-col',(null as any));
    this._Col_23_3 = new import42.Col();
    this._text_24 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'button',(null as any));
    this.renderer.setElementAttribute(this._el_25,'clear','');
    this.renderer.setElementAttribute(this._el_25,'ion-button','');
    this.renderer.setElementAttribute(this._el_25,'primary','');
    this.renderer.setElementAttribute(this._el_25,'small','');
    this._appEl_25 = new import2.AppElement(25,23,this,this._el_25);
    var compView_25:any = import30.viewFactory_Button0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Button_25_4 = new import18.Button((null as any),'',this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_25),this.renderer);
    this._appEl_25.initComponent(this._Button_25_4,[],compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n                        ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_27,'name','md-calendar');
    this.renderer.setElementAttribute(this._el_27,'role','img');
    this._Icon_27_3 = new import19.Icon(this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_27),this.renderer);
    this._text_28 = this.renderer.createText((null as any),'\n                        ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Add to Calendar',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n                    ',(null as any));
      compView_25.create(this._Button_25_4,[[].concat([
        this._text_26,
        this._el_27,
        this._text_28,
        this._el_29,
        this._text_31
      ]
    )],(null as any));
    this._text_32 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._text_33 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_21,'ion-col',(null as any));
    this._Col_34_3 = new import42.Col();
    this._text_35 = this.renderer.createText(this._el_34,'\n                    ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'button',(null as any));
    this.renderer.setElementAttribute(this._el_36,'clear','');
    this.renderer.setElementAttribute(this._el_36,'ion-button','');
    this.renderer.setElementAttribute(this._el_36,'primary','');
    this.renderer.setElementAttribute(this._el_36,'small','');
    this._appEl_36 = new import2.AppElement(36,34,this,this._el_36);
    var compView_36:any = import30.viewFactory_Button0(this.viewUtils,this.injector(36),this._appEl_36);
    this._Button_36_4 = new import18.Button((null as any),'',this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_36),this.renderer);
    this._appEl_36.initComponent(this._Button_36_4,[],compView_36);
    this._text_37 = this.renderer.createText((null as any),'\n                        ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_38,'name','logo-facebook');
    this.renderer.setElementAttribute(this._el_38,'role','img');
    this._Icon_38_3 = new import19.Icon(this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_38),this.renderer);
    this._text_39 = this.renderer.createText((null as any),'\n                        ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'Facebook page',(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n                    ',(null as any));
      compView_36.create(this._Button_36_4,[[].concat([
        this._text_37,
        this._el_38,
        this._text_39,
        this._el_40,
        this._text_42
      ]
    )],(null as any));
    this._text_43 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._text_44 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._text_45 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_25,'click',this.eventHandler(this._handle_click_25_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.CardTitle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._CardTitle_6_3; }
    if (((token === import37.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import40.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6; }
    if (((token === import41.CardContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._CardContent_4_3; }
    if (((token === import19.Icon) && (27 === requestNodeIndex))) { return this._Icon_27_3; }
    if (((token === import18.Button) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Button_25_4; }
    if (((token === import42.Col) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Col_23_3; }
    if (((token === import19.Icon) && (38 === requestNodeIndex))) { return this._Icon_38_3; }
    if (((token === import18.Button) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Button_36_4; }
    if (((token === import42.Col) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Col_34_3; }
    if (((token === import42.Row) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Row_21_3; }
    if (((token === import41.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Card_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    const currVal_6:any = ((this.parent.context.$implicit.basedOn != '') && (this.parent.parent.context.feedType == 'custom'));
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_18_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    changed = false;
    const currVal_8:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._Button_25_4.small = currVal_8;
      changed = true;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._Button_25_4.clear = currVal_9;
      changed = true;
      this._expr_9 = currVal_9;
    }
    if (changed) { this._appEl_25.componentView.markAsCheckOnce(); }
    const currVal_10:any = 'md-calendar';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Icon_27_3.name = currVal_10;
      this._expr_10 = currVal_10;
    }
    changed = false;
    const currVal_12:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Button_36_4.small = currVal_12;
      changed = true;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._Button_36_4.clear = currVal_13;
      changed = true;
      this._expr_13 = currVal_13;
    }
    if (changed) { this._appEl_36.componentView.markAsCheckOnce(); }
    const currVal_14:any = 'logo-facebook';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._Icon_38_3.name = currVal_14;
      this._expr_14 = currVal_14;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_25_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_36_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this.parent.parent.context.clubs[this.parent.context.$implicit.clubRef].banner;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import39.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = import4.interpolate(1,'',this.parent.context.$implicit.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_9,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(2,'',this.parent.context.$implicit.startDate,' | ',this.parent.context.$implicit.location,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_13,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',this.parent.context.$implicit.subheader,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_16,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_11:any = this._Icon_27_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_27,'hide',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_15:any = this._Icon_38_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_38,'hide',currVal_15);
      this._expr_15 = currVal_15;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_27_3.ngOnDestroy();
    this._Icon_38_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.viewEvent(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.viewEvent(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.addToCalendar(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Newsfeed2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_Newsfeed2(viewUtils,parentInjector,declarationEl);
}
class _View_Newsfeed3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Newsfeed3,renderType_Newsfeed,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Based on your interest in ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'b',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.parent.context.$implicit.basedOn,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Newsfeed3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_Newsfeed3(viewUtils,parentInjector,declarationEl);
}