/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './clubselector';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/LocalData';
import * as import10 from 'ionic-angular/components/toast/toast';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from 'ionic-angular/components/toolbar/toolbar';
import * as import14 from 'ionic-angular/components/navbar/navbar';
import * as import15 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import16 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from 'ionic-angular/components/button/button';
import * as import19 from '@angular/forms/src/directives/ng_model';
import * as import20 from '@angular/forms/src/directives/ng_control_status';
import * as import21 from 'ionic-angular/components/segment/segment';
import * as import22 from 'ionic-angular/components/content/content';
import * as import23 from '@angular/common/src/directives/ng_switch';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import30 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/segment/segment.ngfactory';
import * as import32 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import33 from 'ionic-angular/util/keyboard';
import * as import34 from '@angular/core/src/zone/ng_zone';
import * as import35 from 'ionic-angular/components/tabs/tabs';
import * as import36 from '@angular/core/src/linker/template_ref';
import * as import37 from '@angular/forms/src/directives/ng_control';
import * as import38 from '@angular/common/src/directives/ng_for';
import * as import39 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import40 from '@angular/common/src/directives/ng_class';
import * as import41 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import42 from '@angular/core/src/security';
import * as import43 from 'ionic-angular/components/item/item';
import * as import44 from 'ionic-angular/components/list/list-header';
import * as import45 from 'ionic-angular/components/card/card';
import * as import46 from 'ionic-angular/components/list/list';
import * as import47 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import48 from 'ionic-angular/util/form';
import * as import49 from 'ionic-angular/gestures/gesture-controller';
import * as import50 from 'ionic-angular/components/label/label';
import * as import51 from 'ionic-angular/components/toggle/toggle';
import * as import52 from '../../node_modules/ionic-angular/components/toggle/toggle.ngfactory';
import * as import53 from '@angular/forms/src/directives/control_value_accessor';
var renderType_ClubSelector_Host:import0.RenderComponentType = (null as any);
class _View_ClubSelector_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ClubSelector_0_4:import3.ClubSelector;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubSelector_Host0,renderType_ClubSelector_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('flexbox',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ClubSelector0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ClubSelector_0_4 = new import3.ClubSelector(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.LocalData),this.parentInjector.get(import10.ToastController));
    this._appEl_0.initComponent(this._ClubSelector_0_4,[],compView_0);
    compView_0.create(this._ClubSelector_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ClubSelector) && (0 === requestNodeIndex))) { return this._ClubSelector_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ClubSelector_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ClubSelector_Host === (null as any))) { (renderType_ClubSelector_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_ClubSelector_Host0(viewUtils,parentInjector,declarationEl);
}
export const ClubSelectorNgFactory:import12.ComponentFactory<import3.ClubSelector> = new import12.ComponentFactory<import3.ClubSelector>('flexbox',viewFactory_ClubSelector_Host0,import3.ClubSelector);
const styles_ClubSelector:any[] = [];
var renderType_ClubSelector:import0.RenderComponentType = (null as any);
class _View_ClubSelector0 extends import1.AppView<import3.ClubSelector> {
  _el_0:any;
  _Header_0_3:import13.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import14.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import15.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _ToolbarItem_7_3:import16.ToolbarItem;
  _query_Button_7_0:import17.QueryList<any>;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Button_9_4:import18.Button;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _NgModel_14_3:import19.NgModel;
  _NgControl_14_4:any;
  _NgControlStatus_14_5:import20.NgControlStatus;
  _Segment_14_6:import21.Segment;
  _query_SegmentButton_14_0:import17.QueryList<any>;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _SegmentButton_16_4:import21.SegmentButton;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _SegmentButton_19_4:import21.SegmentButton;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _Content_25_4:import22.Content;
  _text_26:any;
  _el_27:any;
  _NgSwitch_27_3:import23.NgSwitch;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _TemplateRef_29_5:any;
  _NgSwitchCase_29_6:import23.NgSwitchCase;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _TemplateRef_31_5:any;
  _NgSwitchCase_31_6:import23.NgSwitchCase;
  _text_32:any;
  _text_33:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubSelector0,renderType_ClubSelector,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','laz-purple');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import27.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Navbar(this.parentInjector.get(import28.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import29.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import15.ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import13.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'Set Preferences',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_7,'end','');
    this._ToolbarItem_7_3 = new import16.ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import13.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_7_0 = new import17.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'ion-button','');
    this.renderer.setElementAttribute(this._el_9,'side','right');
    this._appEl_9 = new import2.AppElement(9,7,this,this._el_9);
    var compView_9:any = import30.viewFactory_Button0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Button_9_4 = new import18.Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_9),this.renderer);
    this._appEl_9.initComponent(this._Button_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'Save',(null as any));
    compView_9.create(this._Button_9_4,[[].concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [].concat([this._el_7]),
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6,
        this._text_12
      ]
      )
    ]
    ,(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_0,'ion-segment',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','newsfeed-segment');
    this.renderer.setElementAttribute(this._el_14,'color','light');
    this._NgModel_14_3 = new import19.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_14_4 = this._NgModel_14_3;
    this._NgControlStatus_14_5 = new import20.NgControlStatus(this._NgControl_14_4);
    this._Segment_14_6 = new import21.Segment(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_14),this.renderer,this._NgControl_14_4);
    this._query_SegmentButton_14_0 = new import17.QueryList<any>();
    this._text_15 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','newsfeed-segment-button segment-button');
    this.renderer.setElementAttribute(this._el_16,'role','button');
    this.renderer.setElementAttribute(this._el_16,'tappable','');
    this.renderer.setElementAttribute(this._el_16,'value','clubs');
    this._appEl_16 = new import2.AppElement(16,14,this,this._el_16);
    var compView_16:any = import31.viewFactory_SegmentButton0(this.viewUtils,this.injector(16),this._appEl_16);
    this._SegmentButton_16_4 = new import21.SegmentButton(this.renderer,new import25.ElementRef(this._el_16));
    this._appEl_16.initComponent(this._SegmentButton_16_4,[],compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n           Clubs\n        ',(null as any));
    compView_16.create(this._SegmentButton_16_4,[[].concat([this._text_17])],(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_14,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','newsfeed-segment-button segment-button');
    this.renderer.setElementAttribute(this._el_19,'role','button');
    this.renderer.setElementAttribute(this._el_19,'tappable','');
    this.renderer.setElementAttribute(this._el_19,'value','interests');
    this._appEl_19 = new import2.AppElement(19,14,this,this._el_19);
    var compView_19:any = import31.viewFactory_SegmentButton0(this.viewUtils,this.injector(19),this._appEl_19);
    this._SegmentButton_19_4 = new import21.SegmentButton(this.renderer,new import25.ElementRef(this._el_19));
    this._appEl_19.initComponent(this._SegmentButton_19_4,[],compView_19);
    this._text_20 = this.renderer.createText((null as any),'\n            Interests\n        ',(null as any));
    compView_19.create(this._SegmentButton_19_4,[[].concat([this._text_20])],(null as any));
    this._text_21 = this.renderer.createText(this._el_14,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_24 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_25 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_25 = new import2.AppElement(25,(null as any),this,this._el_25);
    var compView_25:any = import32.viewFactory_Content0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Content_25_4 = new import22.Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_25),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import33.Keyboard),this.parentInjector.get(import34.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import35.Tabs,(null as any)));
    this._appEl_25.initComponent(this._Content_25_4,[],compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'div',(null as any));
    this._NgSwitch_27_3 = new import23.NgSwitch();
    this._text_28 = this.renderer.createText(this._el_27,' \n        ',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_29 = new import2.AppElement(29,27,this,this._anchor_29);
    this._TemplateRef_29_5 = new import36.TemplateRef_(this._appEl_29,viewFactory_ClubSelector1);
    this._NgSwitchCase_29_6 = new import23.NgSwitchCase(this._appEl_29.vcRef,this._TemplateRef_29_5,this._NgSwitch_27_3);
    this._text_30 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._anchor_31 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_31 = new import2.AppElement(31,27,this,this._anchor_31);
    this._TemplateRef_31_5 = new import36.TemplateRef_(this._appEl_31,viewFactory_ClubSelector3);
    this._NgSwitchCase_31_6 = new import23.NgSwitchCase(this._appEl_31.vcRef,this._TemplateRef_31_5,this._NgSwitch_27_3);
    this._text_32 = this.renderer.createText(this._el_27,'\n    ',(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n',(null as any));
    compView_25.create(this._Content_25_4,[
      [],
      [].concat([
        this._text_26,
        this._el_27,
        this._text_33
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_14,'ngModelChange',this.eventHandler(this._handle_ngModelChange_14_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_14_3.update.subscribe(this.eventHandler(this._handle_ngModelChange_14_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_16,'click',this.eventHandler(this._handle_click_16_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._text_33
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import18.Button) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Button_9_4; }
    if (((token === import16.ToolbarItem) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarItem_7_3; }
    if (((token === import14.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Navbar_2_4; }
    if (((token === import21.SegmentButton) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._SegmentButton_16_4; }
    if (((token === import21.SegmentButton) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._SegmentButton_19_4; }
    if (((token === import19.NgModel) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._NgModel_14_3; }
    if (((token === import37.NgControl) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._NgControl_14_4; }
    if (((token === import20.NgControlStatus) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._NgControlStatus_14_5; }
    if (((token === import21.Segment) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Segment_14_6; }
    if (((token === import13.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Header_0_3; }
    if (((token === import36.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import23.NgSwitchCase) && (29 === requestNodeIndex))) { return this._NgSwitchCase_29_6; }
    if (((token === import36.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import23.NgSwitchCase) && (31 === requestNodeIndex))) { return this._NgSwitchCase_31_6; }
    if (((token === import23.NgSwitch) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgSwitch_27_3; }
    if (((token === import22.Content) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Content_25_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_0:any = 'laz-purple';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_2_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    changes = (null as any);
    const currVal_5:any = this.context.view;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgModel_14_3.model = currVal_5;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    if ((changes !== (null as any))) { this._NgModel_14_3.ngOnChanges(changes); }
    const currVal_12:any = 'light';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Segment_14_6.color = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = 'clubs';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._SegmentButton_16_4.value = currVal_14;
      this._expr_14 = currVal_14;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_16_4.ngOnInit(); }
    const currVal_16:any = 'interests';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._SegmentButton_19_4.value = currVal_16;
      this._expr_16 = currVal_16;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_19_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_25_4.ngOnInit(); }
    const currVal_18:any = this.context.view;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._NgSwitch_27_3.ngSwitch = currVal_18;
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = 'clubs';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._NgSwitchCase_29_6.ngSwitchCase = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = 'interests';
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._NgSwitchCase_31_6.ngSwitchCase = currVal_20;
      this._expr_20 = currVal_20;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_7_0.dirty) {
        this._query_Button_7_0.reset([this._Button_9_4]);
        this._ToolbarItem_7_3._buttons = this._query_Button_7_0;
        this._query_Button_7_0.notifyOnChanges();
      }
      if (this._query_SegmentButton_14_0.dirty) {
        this._query_SegmentButton_14_0.reset([
          this._SegmentButton_16_4,
          this._SegmentButton_19_4
        ]
        );
        this._Segment_14_6._buttons = this._query_SegmentButton_14_0;
        this._query_SegmentButton_14_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_9_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_6:any = this._NgControlStatus_14_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_14,'ng-untouched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_14_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'ng-touched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_14_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_14,'ng-pristine',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_14_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_14,'ng-dirty',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_14_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_14,'ng-valid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_14_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_14,'ng-invalid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_17:any = this._Content_25_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_25,'statusbar-padding',currVal_17);
      this._expr_17 = currVal_17;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Segment_14_6.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._NgModel_14_3.ngOnDestroy();
    this._Content_25_4.ngOnDestroy();
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.savePrefs()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.view = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_16_0($event:any):boolean {
    this._appEl_16.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_16_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this._appEl_19.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_19_4.onClick()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ClubSelector0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ClubSelector> {
  if ((renderType_ClubSelector === (null as any))) { (renderType_ClubSelector = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_ClubSelector,{})); }
  return new _View_ClubSelector0(viewUtils,parentInjector,declarationEl);
}
class _View_ClubSelector1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import38.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubSelector1,renderType_ClubSelector,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','flexbox');
    this.renderer.setElementAttribute(this._el_0,'ion-list','');
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import36.TemplateRef_(this._appEl_2,viewFactory_ClubSelector2);
    this._NgFor_2_6 = new import38.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import39.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import38.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.clubs;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ClubSelector1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubSelector1(viewUtils,parentInjector,declarationEl);
}
class _View_ClubSelector2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _NgClass_7_3:import40.NgClass;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  _map_0:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubSelector2,renderType_ClubSelector,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','selectionbox');
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','infobox');
    this._el_3 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_3,'src','img/info-icon.png');
    this._text_4 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n                    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'img',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','unchecked-clubs-page');
    this._NgClass_7_3 = new import40.NgClass(this.parent.parent.parentInjector.get(import39.IterableDiffers),this.parent.parent.parentInjector.get(import41.KeyValueDiffers),new import25.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'checked-clubs-page': p0,
        'unchecked-clubs-page': p1
      }
      ;
    });
    this._expr_4 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import40.NgClass) && (7 === requestNodeIndex))) { return this._NgClass_7_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = 'unchecked-clubs-page';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgClass_7_3.klass = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._map_0(this.context.$implicit.selected,!this.context.$implicit.selected);
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgClass_7_3.ngClass = currVal_4;
      this._expr_4 = currVal_4;
    }
    if (!throwOnChange) { this._NgClass_7_3.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.logo,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_7,'src',this.viewUtils.sanitizer.sanitize(import42.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.viewClub(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.toggle(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ClubSelector2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubSelector2(viewUtils,parentInjector,declarationEl);
}
class _View_ClubSelector3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import43.Item;
  _ListHeader_2_5:import44.ListHeader;
  _query_Label_2_0:import17.QueryList<any>;
  _query_Button_2_1:import17.QueryList<any>;
  _query_Icon_2_2:import17.QueryList<any>;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _Card_5_3:import45.Card;
  _text_6:any;
  _el_7:any;
  _List_7_3:import46.List;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _TemplateRef_9_5:any;
  _NgFor_9_6:import38.NgFor;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubSelector3,renderType_ClubSelector,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import47.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import43.Item(this.parent.parentInjector.get(import48.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._ListHeader_2_5 = new import44.ListHeader(this.parent.parentInjector.get(import24.Config),this.renderer,new import25.ElementRef(this._el_2),(null as any));
    this._query_Label_2_0 = new import17.QueryList<any>();
    this._query_Button_2_1 = new import17.QueryList<any>();
    this._query_Icon_2_2 = new import17.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'What are you interested in?',(null as any));
    this._query_Label_2_0.reset([]);
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      [],
      [],
      [].concat([this._text_3]),
      [],
      []
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'ion-card',(null as any));
    this._Card_5_3 = new import45.Card(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer);
    this._text_6 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'ion-list',(null as any));
    this._List_7_3 = new import46.List(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_7),this.renderer,this.parent.parentInjector.get(import49.GestureController));
    this._text_8 = this.renderer.createText(this._el_7,'\n                    ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_9 = new import2.AppElement(9,7,this,this._anchor_9);
    this._TemplateRef_9_5 = new import36.TemplateRef_(this._appEl_9,viewFactory_ClubSelector4);
    this._NgFor_9_6 = new import38.NgFor(this._appEl_9.vcRef,this._TemplateRef_9_5,this.parent.parentInjector.get(import39.IterableDiffers),this.parent.ref);
    this._text_10 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import43.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_2_4; }
    if (((token === import44.ListHeader) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ListHeader_2_5; }
    if (((token === import36.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import38.NgFor) && (9 === requestNodeIndex))) { return this._NgFor_9_6; }
    if (((token === import46.List) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._List_7_3; }
    if (((token === import45.Card) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Card_5_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.interests;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_9_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_9_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_9_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([]);
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset([]);
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ClubSelector3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubSelector3(viewUtils,parentInjector,declarationEl);
}
class _View_ClubSelector4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import43.Item;
  _ItemContent_0_5:import43.ItemContent;
  _query_Label_0_0:import17.QueryList<any>;
  _query_Button_0_1:import17.QueryList<any>;
  _query_Icon_0_2:import17.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Label_2_3:import50.Label;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _Toggle_5_4:import51.Toggle;
  _NG_VALUE_ACCESSOR_5_5:any[];
  _NgModel_5_6:import19.NgModel;
  _NgControl_5_7:any;
  _NgControlStatus_5_8:import20.NgControlStatus;
  _text_6:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubSelector4,renderType_ClubSelector,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import47.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import43.Item(this.parent.parent.parentInjector.get(import48.Form),this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import43.ItemContent();
    this._query_Label_0_0 = new import17.QueryList<any>();
    this._query_Button_0_1 = new import17.QueryList<any>();
    this._query_Icon_0_2 = new import17.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n                        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_2_3 = new import50.Label(this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n                        ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_5,'laz-purple','');
    this._appEl_5 = new import2.AppElement(5,0,this,this._el_5);
    var compView_5:any = import52.viewFactory_Toggle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Toggle_5_4 = new import51.Toggle(this.parent.parent.parentInjector.get(import48.Form),this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer,this._Item_0_4);
    this._NG_VALUE_ACCESSOR_5_5 = [this._Toggle_5_4];
    this._NgModel_5_6 = new import19.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_5_5);
    this._NgControl_5_7 = this._NgModel_5_6;
    this._NgControlStatus_5_8 = new import20.NgControlStatus(this._NgControl_5_7);
    this._appEl_5.initComponent(this._Toggle_5_4,[],compView_5);
    compView_5.create(this._Toggle_5_4,[],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._query_Label_0_0.reset([this._Label_2_3]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [],
      [].concat([this._el_2]),
      [].concat([
        this._text_1,
        this._text_4,
        this._text_6
      ]
      ),
      [],
      [].concat([this._el_5])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'ngModelChange',this.eventHandler(this._handle_ngModelChange_5_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_5_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_5_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import50.Label) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Label_2_3; }
    if (((token === import51.Toggle) && (5 === requestNodeIndex))) { return this._Toggle_5_4; }
    if (((token === import53.NG_VALUE_ACCESSOR) && (5 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_5_5; }
    if (((token === import19.NgModel) && (5 === requestNodeIndex))) { return this._NgModel_5_6; }
    if (((token === import37.NgControl) && (5 === requestNodeIndex))) { return this._NgControl_5_7; }
    if (((token === import20.NgControlStatus) && (5 === requestNodeIndex))) { return this._NgControlStatus_5_8; }
    if (((token === import43.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Item_0_4; }
    if (((token === import43.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ItemContent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = this.context.$implicit.selected;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgModel_5_6.model = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgModel_5_6.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Toggle_5_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = this._Toggle_5_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_5,'toggle-disabled',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._NgControlStatus_5_8.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_5,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatus_5_8.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_5,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_5_8.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_5,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_5_8.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_5,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_5_8.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_5,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_5_8.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_5,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Toggle_5_4.ngOnDestroy();
    this._NgModel_5_6.ngOnDestroy();
  }
  private _handle_ngModelChange_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.$implicit.selected = $event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ClubSelector4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubSelector4(viewUtils,parentInjector,declarationEl);
}