/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './clubpage';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '../../providers/LocalData';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from 'ionic-angular/components/toolbar/toolbar';
import * as import14 from 'ionic-angular/components/navbar/navbar';
import * as import15 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import16 from 'ionic-angular/components/content/content';
import * as import17 from '@angular/common/src/directives/ng_if';
import * as import18 from 'ionic-angular/components/card/card';
import * as import19 from 'ionic-angular/components/item/item';
import * as import20 from 'ionic-angular/components/list/list-header';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from '@angular/common/src/directives/ng_for';
import * as import23 from 'ionic-angular/components/fab/fab';
import * as import24 from 'ionic-angular/components/icon/icon';
import * as import25 from '../../pipes/MapToIterablePipe';
import * as import26 from '../../pipes/GetLongDate';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from '@angular/core/src/linker/element_ref';
import * as import29 from 'ionic-angular/navigation/view-controller';
import * as import30 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import31 from 'ionic-angular/components/app/app';
import * as import32 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import33 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import34 from 'ionic-angular/util/keyboard';
import * as import35 from '@angular/core/src/zone/ng_zone';
import * as import36 from 'ionic-angular/components/tabs/tabs';
import * as import37 from '@angular/core/src/linker/template_ref';
import * as import38 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import39 from 'ionic-angular/util/form';
import * as import40 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import41 from '../../node_modules/ionic-angular/components/fab/fab.ngfactory';
import * as import42 from '@angular/core/src/security';
import * as import43 from 'ionic-angular/components/button/button';
import * as import44 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import45 from 'ionic-angular/components/grid/grid';
var renderType_ClubPage_Host:import0.RenderComponentType = (null as any);
class _View_ClubPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ClubPage_0_4:import3.ClubPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage_Host0,renderType_ClubPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ClubPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ClubPage_0_4 = new import3.ClubPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.LocalData));
    this._appEl_0.initComponent(this._ClubPage_0_4,[],compView_0);
    compView_0.create(this._ClubPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ClubPage) && (0 === requestNodeIndex))) { return this._ClubPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ClubPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ClubPage_Host === (null as any))) { (renderType_ClubPage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_ClubPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ClubPageNgFactory:import12.ComponentFactory<import3.ClubPage> = new import12.ComponentFactory<import3.ClubPage>('ng-component',viewFactory_ClubPage_Host0,import3.ClubPage);
const styles_ClubPage:any[] = [];
var renderType_ClubPage:import0.RenderComponentType = (null as any);
class _View_ClubPage0 extends import1.AppView<import3.ClubPage> {
  _el_0:any;
  _Header_0_3:import13.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import14.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import15.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import16.Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import17.NgIf;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import17.NgIf;
  _text_16:any;
  _el_17:any;
  _Card_17_3:import18.Card;
  _text_18:any;
  _el_19:any;
  _CardHeader_19_3:import18.CardHeader;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _CardContent_23_3:import18.CardContent;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _Item_27_4:import19.Item;
  _ListHeader_27_5:import20.ListHeader;
  _query_Label_27_0:import21.QueryList<any>;
  _query_Button_27_1:import21.QueryList<any>;
  _query_Icon_27_2:import21.QueryList<any>;
  _text_28:any;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _TemplateRef_30_5:any;
  _NgFor_30_6:import22.NgFor;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _FabContainer_32_4:import23.FabContainer;
  _query_FabButton_32_0:import21.QueryList<any>;
  _query_FabList_32_1:import21.QueryList<any>;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _FabButton_34_4:import23.FabButton;
  _el_35:any;
  _Icon_35_3:import24.Icon;
  _text_36:any;
  _el_37:any;
  _FabList_37_3:import23.FabList;
  _query_FabButton_37_0:import21.QueryList<any>;
  _text_38:any;
  _anchor_39:any;
  /*private*/ _appEl_39:import2.AppElement;
  _TemplateRef_39_5:any;
  _NgIf_39_6:import17.NgIf;
  _text_40:any;
  _anchor_41:any;
  /*private*/ _appEl_41:import2.AppElement;
  _TemplateRef_41_5:any;
  _NgIf_41_6:import17.NgIf;
  _text_42:any;
  _anchor_43:any;
  /*private*/ _appEl_43:import2.AppElement;
  _TemplateRef_43_5:any;
  _NgIf_43_6:import17.NgIf;
  _text_44:any;
  _anchor_45:any;
  /*private*/ _appEl_45:import2.AppElement;
  _TemplateRef_45_5:any;
  _NgIf_45_6:import17.NgIf;
  _text_46:any;
  _anchor_47:any;
  /*private*/ _appEl_47:import2.AppElement;
  _TemplateRef_47_5:any;
  _NgIf_47_6:import17.NgIf;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  _pipe_mapToIterable_0:import25.MapToIterablePipe;
  _pipe_mapToIterable_0_0:any;
  /*private*/ _expr_10:any;
  _pipe_getLongDate_1:import26.GetLongDate;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage0,renderType_ClubPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Header(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','laz-purple');
    this.renderer.setElementAttribute(this._el_2,'style','border-bottom:2px solid #F2A900');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import30.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Navbar(this.parentInjector.get(import31.App),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import32.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import15.ToolbarTitle(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import13.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import33.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import16.Content(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import31.App),this.parentInjector.get(import34.Keyboard),this.parentInjector.get(import35.NgZone),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import36.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'img',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_13 = new import2.AppElement(13,9,this,this._anchor_13);
    this._TemplateRef_13_5 = new import37.TemplateRef_(this._appEl_13,viewFactory_ClubPage1);
    this._NgIf_13_6 = new import17.NgIf(this._appEl_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_15 = new import2.AppElement(15,9,this,this._anchor_15);
    this._TemplateRef_15_5 = new import37.TemplateRef_(this._appEl_15,viewFactory_ClubPage2);
    this._NgIf_15_6 = new import17.NgIf(this._appEl_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_17_3 = new import18.Card(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'ion-card-header',(null as any));
    this._CardHeader_19_3 = new import18.CardHeader();
    this._el_20 = this.renderer.createElement(this._el_19,'b',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'',(null as any));
    this._text_22 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_17,'ion-card-content',(null as any));
    this._CardContent_23_3 = new import18.CardContent();
    this._text_24 = this.renderer.createText(this._el_23,'',(null as any));
    this._text_25 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','item');
    this._appEl_27 = new import2.AppElement(27,9,this,this._el_27);
    var compView_27:any = import38.viewFactory_Item0(this.viewUtils,this.injector(27),this._appEl_27);
    this._Item_27_4 = new import19.Item(this.parentInjector.get(import39.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_27),this.renderer);
    this._ListHeader_27_5 = new import20.ListHeader(this.parentInjector.get(import27.Config),this.renderer,new import28.ElementRef(this._el_27),(null as any));
    this._query_Label_27_0 = new import21.QueryList<any>();
    this._query_Button_27_1 = new import21.QueryList<any>();
    this._query_Icon_27_2 = new import21.QueryList<any>();
    this._appEl_27.initComponent(this._Item_27_4,[],compView_27);
    this._text_28 = this.renderer.createText((null as any),'Upcoming events:',(null as any));
    this._query_Label_27_0.reset([]);
    this._Item_27_4.contentLabel = this._query_Label_27_0.first;
    compView_27.create(this._Item_27_4,[
      [],
      [],
      [].concat([this._text_28]),
      [],
      []
    ]
    ,(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_30 = new import2.AppElement(30,9,this,this._anchor_30);
    this._TemplateRef_30_5 = new import37.TemplateRef_(this._appEl_30,viewFactory_ClubPage3);
    this._NgFor_30_6 = new import22.NgFor(this._appEl_30.vcRef,this._TemplateRef_30_5,this.parentInjector.get(import40.IterableDiffers),this.ref);
    this._text_31 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-fab',(null as any));
    this.renderer.setElementAttribute(this._el_32,'right','');
    this.renderer.setElementAttribute(this._el_32,'top','');
    this._appEl_32 = new import2.AppElement(32,9,this,this._el_32);
    var compView_32:any = import41.viewFactory_FabContainer0(this.viewUtils,this.injector(32),this._appEl_32);
    this._FabContainer_32_4 = new import23.FabContainer(new import28.ElementRef(this._el_32));
    this._query_FabButton_32_0 = new import21.QueryList<any>();
    this._query_FabList_32_1 = new import21.QueryList<any>();
    this._appEl_32.initComponent(this._FabContainer_32_4,[],compView_32);
    this._text_33 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_34,'color','danger');
    this.renderer.setElementAttribute(this._el_34,'ion-fab','');
    this._appEl_34 = new import2.AppElement(34,32,this,this._el_34);
    var compView_34:any = import41.viewFactory_FabButton0(this.viewUtils,this.injector(34),this._appEl_34);
    this._FabButton_34_4 = new import23.FabButton(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_34),this.renderer);
    this._appEl_34.initComponent(this._FabButton_34_4,[],compView_34);
    this._el_35 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_35,'name','md-share');
    this.renderer.setElementAttribute(this._el_35,'role','img');
    this._Icon_35_3 = new import24.Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_35),this.renderer);
    compView_34.create(this._FabButton_34_4,[[].concat([this._el_35])],(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-fab-list',(null as any));
    this.renderer.setElementAttribute(this._el_37,'side','bottom');
    this._FabList_37_3 = new import23.FabList(new import28.ElementRef(this._el_37),this.renderer);
    this._query_FabButton_37_0 = new import21.QueryList<any>();
    this._text_38 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._anchor_39 = this.renderer.createTemplateAnchor(this._el_37,(null as any));
    this._appEl_39 = new import2.AppElement(39,37,this,this._anchor_39);
    this._TemplateRef_39_5 = new import37.TemplateRef_(this._appEl_39,viewFactory_ClubPage7);
    this._NgIf_39_6 = new import17.NgIf(this._appEl_39.vcRef,this._TemplateRef_39_5);
    this._text_40 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._anchor_41 = this.renderer.createTemplateAnchor(this._el_37,(null as any));
    this._appEl_41 = new import2.AppElement(41,37,this,this._anchor_41);
    this._TemplateRef_41_5 = new import37.TemplateRef_(this._appEl_41,viewFactory_ClubPage8);
    this._NgIf_41_6 = new import17.NgIf(this._appEl_41.vcRef,this._TemplateRef_41_5);
    this._text_42 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._anchor_43 = this.renderer.createTemplateAnchor(this._el_37,(null as any));
    this._appEl_43 = new import2.AppElement(43,37,this,this._anchor_43);
    this._TemplateRef_43_5 = new import37.TemplateRef_(this._appEl_43,viewFactory_ClubPage9);
    this._NgIf_43_6 = new import17.NgIf(this._appEl_43.vcRef,this._TemplateRef_43_5);
    this._text_44 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._anchor_45 = this.renderer.createTemplateAnchor(this._el_37,(null as any));
    this._appEl_45 = new import2.AppElement(45,37,this,this._anchor_45);
    this._TemplateRef_45_5 = new import37.TemplateRef_(this._appEl_45,viewFactory_ClubPage10);
    this._NgIf_45_6 = new import17.NgIf(this._appEl_45.vcRef,this._TemplateRef_45_5);
    this._text_46 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._anchor_47 = this.renderer.createTemplateAnchor(this._el_37,(null as any));
    this._appEl_47 = new import2.AppElement(47,37,this,this._anchor_47);
    this._TemplateRef_47_5 = new import37.TemplateRef_(this._appEl_47,viewFactory_ClubPage11);
    this._NgIf_47_6 = new import17.NgIf(this._appEl_47.vcRef,this._TemplateRef_47_5);
    this._text_48 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_FabButton_32_0.reset([this._FabButton_34_4]);
    this._FabContainer_32_4._mainButton = this._query_FabButton_32_0.first;
      compView_32.create(this._FabContainer_32_4,[[].concat([
        this._text_33,
        this._el_34,
        this._text_36,
        this._el_37,
        this._text_49
      ]
    )],(null as any));
    this._text_50 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4,[
      [].concat([this._el_32]),
      [].concat([
        this._text_10,
        this._el_11,
        this._text_12,
        this._appEl_13,
        this._text_14,
        this._appEl_15,
        this._text_16,
        this._el_17,
        this._text_26,
        this._el_27,
        this._text_29,
        this._appEl_30,
        this._text_31,
        this._text_50
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._pipe_mapToIterable_0 = new import25.MapToIterablePipe();
    this._pipe_mapToIterable_0_0 = import4.pureProxy1(this._pipe_mapToIterable_0.transform.bind(this._pipe_mapToIterable_0));
    this._expr_10 = import7.UNINITIALIZED;
    this._pipe_getLongDate_1 = new import26.GetLongDate();
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._anchor_39,
      this._text_40,
      this._anchor_41,
      this._text_42,
      this._anchor_43,
      this._text_44,
      this._anchor_45,
      this._text_46,
      this._anchor_47,
      this._text_48,
      this._text_49,
      this._text_50
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import14.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import13.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import37.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import17.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6; }
    if (((token === import37.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import17.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6; }
    if (((token === import18.CardHeader) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._CardHeader_19_3; }
    if (((token === import18.CardContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._CardContent_23_3; }
    if (((token === import18.Card) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Card_17_3; }
    if (((token === import19.Item) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Item_27_4; }
    if (((token === import20.ListHeader) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ListHeader_27_5; }
    if (((token === import37.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import22.NgFor) && (30 === requestNodeIndex))) { return this._NgFor_30_6; }
    if (((token === import24.Icon) && (35 === requestNodeIndex))) { return this._Icon_35_3; }
    if (((token === import23.FabButton) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._FabButton_34_4; }
    if (((token === import37.TemplateRef) && (39 === requestNodeIndex))) { return this._TemplateRef_39_5; }
    if (((token === import17.NgIf) && (39 === requestNodeIndex))) { return this._NgIf_39_6; }
    if (((token === import37.TemplateRef) && (41 === requestNodeIndex))) { return this._TemplateRef_41_5; }
    if (((token === import17.NgIf) && (41 === requestNodeIndex))) { return this._NgIf_41_6; }
    if (((token === import37.TemplateRef) && (43 === requestNodeIndex))) { return this._TemplateRef_43_5; }
    if (((token === import17.NgIf) && (43 === requestNodeIndex))) { return this._NgIf_43_6; }
    if (((token === import37.TemplateRef) && (45 === requestNodeIndex))) { return this._TemplateRef_45_5; }
    if (((token === import17.NgIf) && (45 === requestNodeIndex))) { return this._NgIf_45_6; }
    if (((token === import37.TemplateRef) && (47 === requestNodeIndex))) { return this._TemplateRef_47_5; }
    if (((token === import17.NgIf) && (47 === requestNodeIndex))) { return this._NgIf_47_6; }
    if (((token === import23.FabList) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._FabList_37_3; }
    if (((token === import23.FabContainer) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._FabContainer_32_4; }
    if (((token === import16.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_0:any = 'laz-purple';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_2_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    const currVal_6:boolean = !this.context.prefs.clubPrefs[this.context.club.id.toString()].selected;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_13_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.context.prefs.clubPrefs[this.context.club.id.toString()].selected;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgIf_15_6.ngIf = currVal_7;
      this._expr_7 = currVal_7;
    }
    changes = (null as any);
    valUnwrapper.reset();
    const currVal_10:any = valUnwrapper.unwrap(import4.castByValue(this._pipe_mapToIterable_0_0,this._pipe_mapToIterable_0.transform)(this.context.events));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_10,currVal_10))) {
      this._NgFor_30_6.ngForOf = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgFor_30_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_30_6.ngDoCheck(); }
    changed = false;
    const currVal_11:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._FabButton_34_4.color = currVal_11;
      changed = true;
      this._expr_11 = currVal_11;
    }
    if (changed) { this._appEl_34.componentView.markAsCheckOnce(); }
    const currVal_12:any = 'md-share';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Icon_35_3.name = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = this.context.club.club_social_links['facebook'];
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgIf_39_6.ngIf = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.context.club.club_social_links['twitter'];
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgIf_41_6.ngIf = currVal_15;
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this.context.club.club_social_links['instagram'];
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._NgIf_43_6.ngIf = currVal_16;
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this.context.club.club_social_links['snapchat'];
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._NgIf_45_6.ngIf = currVal_17;
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this.context.club.club_social_links['youtube'];
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._NgIf_47_6.ngIf = currVal_18;
      this._expr_18 = currVal_18;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_27_1.dirty) {
        this._query_Button_27_1.reset([]);
        this._Item_27_4._buttons = this._query_Button_27_1;
        this._query_Button_27_1.notifyOnChanges();
      }
      if (this._query_Icon_27_2.dirty) {
        this._query_Icon_27_2.reset([]);
        this._Item_27_4._icons = this._query_Icon_27_2;
        this._query_Icon_27_2.notifyOnChanges();
      }
      if (this._query_FabButton_37_0.dirty) {
        this._query_FabButton_37_0.reset([
          this._appEl_39.mapNestedViews(_View_ClubPage7,(nestedView:_View_ClubPage7):any => {
            return [nestedView._FabButton_0_4];
          }),
          this._appEl_41.mapNestedViews(_View_ClubPage8,(nestedView:_View_ClubPage8):any => {
            return [nestedView._FabButton_0_4];
          }),
          this._appEl_43.mapNestedViews(_View_ClubPage9,(nestedView:_View_ClubPage9):any => {
            return [nestedView._FabButton_0_4];
          }),
          this._appEl_45.mapNestedViews(_View_ClubPage10,(nestedView:_View_ClubPage10):any => {
            return [nestedView._FabButton_0_4];
          }),
          this._appEl_47.mapNestedViews(_View_ClubPage11,(nestedView:_View_ClubPage11):any => {
            return [nestedView._FabButton_0_4];
          })
        ]
        );
        this._FabList_37_3._setbuttons = this._query_FabButton_37_0;
        this._query_FabButton_37_0.notifyOnChanges();
      }
      if (this._query_FabList_32_1.dirty) {
        this._query_FabList_32_1.reset([this._FabList_37_3]);
        this._FabContainer_32_4._fabLists = this._query_FabList_32_1;
        this._query_FabList_32_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_27_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._FabContainer_32_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.club.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_5,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'assets/img/',this.context.club.app_banner,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_11,'src',this.viewUtils.sanitizer.sanitize(import42.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = import4.interpolate(1,'',this.context.club.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_21,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import4.interpolate(1,'',this.context.club.description,'');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_24,currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = this._Icon_35_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_35,'hide',currVal_13);
      this._expr_13 = currVal_13;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_35_3.ngOnDestroy();
    this._FabContainer_32_4.ngOnDestroy();
    this._Content_9_4.ngOnDestroy();
  }
}
export function viewFactory_ClubPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ClubPage> {
  if ((renderType_ClubPage === (null as any))) { (renderType_ClubPage = viewUtils.createRenderComponentType('C:/Users/Richard Hugessen/Documents/GitHub/Lazsoc-2.0/.tmp/pages/clubpage/clubpage.html',0,import11.ViewEncapsulation.None,styles_ClubPage,{})); }
  return new _View_ClubPage0(viewUtils,parentInjector,declarationEl);
}
class _View_ClubPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Button_0_4:import43.Button;
  _text_1:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage1,renderType_ClubPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'block','');
    this.renderer.setElementAttribute(this._el_0,'color','primary');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import44.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import43.Button((null as any),'',this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'Click to Subscribe!',(null as any));
    compView_0.create(this._Button_0_4,[[].concat([this._text_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import43.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_0_4.block = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = 'primary';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_0_4.color = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.toggle()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ClubPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubPage1(viewUtils,parentInjector,declarationEl);
}
class _View_ClubPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Button_0_4:import43.Button;
  _text_1:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage2,renderType_ClubPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'block','');
    this.renderer.setElementAttribute(this._el_0,'color','secondary');
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import44.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import43.Button((null as any),'',this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Button_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'Subscribed!',(null as any));
    compView_0.create(this._Button_0_4,[[].concat([this._text_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import43.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Button_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_0_4.block = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = 'secondary';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_0_4.color = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_0_4.ngAfterContentInit(); } }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.toggle()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ClubPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubPage2(viewUtils,parentInjector,declarationEl);
}
class _View_ClubPage3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import19.Item;
  _ListHeader_2_5:import20.ListHeader;
  _query_Label_2_0:import21.QueryList<any>;
  _query_Button_2_1:import21.QueryList<any>;
  _query_Icon_2_2:import21.QueryList<any>;
  _text_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _TemplateRef_5_5:any;
  _NgFor_5_6:import22.NgFor;
  _text_6:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage3,renderType_ClubPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import38.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import19.Item(this.parent.parentInjector.get(import39.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_2),this.renderer);
    this._ListHeader_2_5 = new import20.ListHeader(this.parent.parentInjector.get(import27.Config),this.renderer,new import28.ElementRef(this._el_2),(null as any));
    this._query_Label_2_0 = new import21.QueryList<any>();
    this._query_Button_2_1 = new import21.QueryList<any>();
    this._query_Icon_2_2 = new import21.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_2_0.reset([]);
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      [],
      [],
      [].concat([this._text_3]),
      [],
      []
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_5 = new import2.AppElement(5,0,this,this._anchor_5);
    this._TemplateRef_5_5 = new import37.TemplateRef_(this._appEl_5,viewFactory_ClubPage4);
    this._NgFor_5_6 = new import22.NgFor(this._appEl_5.vcRef,this._TemplateRef_5_5,this.parent.parentInjector.get(import40.IterableDiffers),this.parent.ref);
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._anchor_5,
      this._text_6
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_2_4; }
    if (((token === import20.ListHeader) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ListHeader_2_5; }
    if (((token === import37.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import22.NgFor) && (5 === requestNodeIndex))) { return this._NgFor_5_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this.context.$implicit.val.events;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_5_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_5_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_5_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([]);
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset([]);
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'\n            ',this.context.$implicit.val.divider,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ClubPage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubPage3(viewUtils,parentInjector,declarationEl);
}
class _View_ClubPage4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Card_2_3:import18.Card;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import17.NgIf;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import17.NgIf;
  _text_7:any;
  _el_8:any;
  _CardContent_8_3:import18.CardContent;
  _text_9:any;
  _el_10:any;
  _CardTitle_10_3:import18.CardTitle;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _Row_23_3:import45.Row;
  _text_24:any;
  _el_25:any;
  _Col_25_3:import45.Col;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _Button_27_4:import43.Button;
  _text_28:any;
  _el_29:any;
  _Icon_29_3:import24.Icon;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _Col_36_3:import45.Col;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import2.AppElement;
  _Button_38_4:import43.Button;
  _text_39:any;
  _el_40:any;
  _Icon_40_3:import24.Icon;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  _pipe_getLongDate_1_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage4,renderType_ClubPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_2,'style','border-style:solid black');
    this._Card_2_3 = new import18.Card(this.parent.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import37.TemplateRef_(this._appEl_4,viewFactory_ClubPage5);
    this._NgIf_4_6 = new import17.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_6 = new import2.AppElement(6,2,this,this._anchor_6);
    this._TemplateRef_6_5 = new import37.TemplateRef_(this._appEl_6,viewFactory_ClubPage6);
    this._NgIf_6_6 = new import17.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_2,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_8,'style','padding:1.5%');
    this._CardContent_8_3 = new import18.CardContent();
    this._text_9 = this.renderer.createText(this._el_8,'\n                    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'ion-card-title',(null as any));
    this.renderer.setElementAttribute(this._el_10,'style','font-size:18px');
    this._CardTitle_10_3 = new import18.CardTitle();
    this._text_11 = this.renderer.createText(this._el_10,'\n                        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'b',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'   \n                    ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_8,'p',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_8,'\n                    ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_8,'p',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n                \n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_2,'ion-row',(null as any));
    this._Row_23_3 = new import45.Row();
    this._text_24 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'ion-col',(null as any));
    this._Col_25_3 = new import45.Col();
    this._text_26 = this.renderer.createText(this._el_25,'\n                        ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'button',(null as any));
    this.renderer.setElementAttribute(this._el_27,'clear','');
    this.renderer.setElementAttribute(this._el_27,'ion-button','');
    this.renderer.setElementAttribute(this._el_27,'primary','');
    this.renderer.setElementAttribute(this._el_27,'small','');
    this._appEl_27 = new import2.AppElement(27,25,this,this._el_27);
    var compView_27:any = import44.viewFactory_Button0(this.viewUtils,this.injector(27),this._appEl_27);
    this._Button_27_4 = new import43.Button((null as any),'',this.parent.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_27),this.renderer);
    this._appEl_27.initComponent(this._Button_27_4,[],compView_27);
    this._text_28 = this.renderer.createText((null as any),'\n                            ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_29,'name','md-calendar');
    this.renderer.setElementAttribute(this._el_29,'role','img');
    this._Icon_29_3 = new import24.Icon(this.parent.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_29),this.renderer);
    this._text_30 = this.renderer.createText((null as any),'\n                            ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Add to Calendar',(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n                        ',(null as any));
      compView_27.create(this._Button_27_4,[[].concat([
        this._text_28,
        this._el_29,
        this._text_30,
        this._el_31,
        this._text_33
      ]
    )],(null as any));
    this._text_34 = this.renderer.createText(this._el_25,'\n                    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_23,'ion-col',(null as any));
    this._Col_36_3 = new import45.Col();
    this._text_37 = this.renderer.createText(this._el_36,'\n                        ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'button',(null as any));
    this.renderer.setElementAttribute(this._el_38,'clear','');
    this.renderer.setElementAttribute(this._el_38,'ion-button','');
    this.renderer.setElementAttribute(this._el_38,'primary','');
    this.renderer.setElementAttribute(this._el_38,'small','');
    this._appEl_38 = new import2.AppElement(38,36,this,this._el_38);
    var compView_38:any = import44.viewFactory_Button0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Button_38_4 = new import43.Button((null as any),'',this.parent.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_38),this.renderer);
    this._appEl_38.initComponent(this._Button_38_4,[],compView_38);
    this._text_39 = this.renderer.createText((null as any),'\n                            ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_40,'name','logo-facebook');
    this.renderer.setElementAttribute(this._el_40,'role','img');
    this._Icon_40_3 = new import24.Icon(this.parent.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_40),this.renderer);
    this._text_41 = this.renderer.createText((null as any),'\n                            ',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'Facebook page',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n                        ',(null as any));
      compView_38.create(this._Button_38_4,[[].concat([
        this._text_39,
        this._el_40,
        this._text_41,
        this._el_42,
        this._text_44
      ]
    )],(null as any));
    this._text_45 = this.renderer.createText(this._el_36,'\n                    ',(null as any));
    this._text_46 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._text_47 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._text_48 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._pipe_getLongDate_1_0 = import4.pureProxy1((<_View_ClubPage0>this.parent.parent)._pipe_getLongDate_1.transform.bind((<_View_ClubPage0>this.parent.parent)._pipe_getLongDate_1));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_27,'click',this.eventHandler(this._handle_click_27_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import17.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    if (((token === import37.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import17.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    if (((token === import18.CardTitle) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._CardTitle_10_3; }
    if (((token === import18.CardContent) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._CardContent_8_3; }
    if (((token === import24.Icon) && (29 === requestNodeIndex))) { return this._Icon_29_3; }
    if (((token === import43.Button) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Button_27_4; }
    if (((token === import45.Col) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Col_25_3; }
    if (((token === import24.Icon) && (40 === requestNodeIndex))) { return this._Icon_40_3; }
    if (((token === import43.Button) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Button_38_4; }
    if (((token === import45.Col) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Col_36_3; }
    if (((token === import45.Row) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Row_23_3; }
    if (((token === import18.Card) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Card_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_0:any = (this.context.$implicit.banner != (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_4_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (this.context.$implicit.banner == (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_6_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    changed = false;
    const currVal_7:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Button_27_4.small = currVal_7;
      changed = true;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._Button_27_4.clear = currVal_8;
      changed = true;
      this._expr_8 = currVal_8;
    }
    if (changed) { this._appEl_27.componentView.markAsCheckOnce(); }
    const currVal_9:any = 'md-calendar';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._Icon_29_3.name = currVal_9;
      this._expr_9 = currVal_9;
    }
    changed = false;
    const currVal_11:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Button_38_4.small = currVal_11;
      changed = true;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Button_38_4.clear = currVal_12;
      changed = true;
      this._expr_12 = currVal_12;
    }
    if (changed) { this._appEl_38.componentView.markAsCheckOnce(); }
    const currVal_13:any = 'logo-facebook';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._Icon_40_3.name = currVal_13;
      this._expr_13 = currVal_13;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_27_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_38_4.ngAfterContentInit(); }
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_13,currVal_3);
      this._expr_3 = currVal_3;
    }
    valUnwrapper.reset();
    const currVal_4:any = import4.interpolate(2,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_getLongDate_1_0,(<_View_ClubPage0>this.parent.parent)._pipe_getLongDate_1.transform)(this.context.$implicit.start_date_time)),' | ',this.context.$implicit.location,'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_4,currVal_4))) {
      this.renderer.setText(this._text_17,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',this.context.$implicit.sub_heading,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_20,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_10:any = this._Icon_29_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_29,'hide',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_14:any = this._Icon_40_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_40,'hide',currVal_14);
      this._expr_14 = currVal_14;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_29_3.ngOnDestroy();
    this._Icon_40_3.ngOnDestroy();
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.viewEvent(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.addToCalendar(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ClubPage4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubPage4(viewUtils,parentInjector,declarationEl);
}
class _View_ClubPage5 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage5,renderType_ClubPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.$implicit.banner;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import42.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ClubPage5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubPage5(viewUtils,parentInjector,declarationEl);
}
class _View_ClubPage6 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage6,renderType_ClubPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import4.interpolate(1,'assets/img/',this.parent.parent.parent.context.club.app_banner,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import42.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.viewEvent(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ClubPage6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubPage6(viewUtils,parentInjector,declarationEl);
}
class _View_ClubPage7 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FabButton_0_4:import23.FabButton;
  _el_1:any;
  _Icon_1_3:import24.Icon;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage7,renderType_ClubPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','facebook');
    this.renderer.setElementAttribute(this._el_0,'ion-fab','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import41.viewFactory_FabButton0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FabButton_0_4 = new import23.FabButton(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._FabButton_0_4,[],compView_0);
    this._el_1 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_1,'name','logo-facebook');
    this.renderer.setElementAttribute(this._el_1,'role','img');
    this._Icon_1_3 = new import24.Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_1),this.renderer);
    compView_0.create(this._FabButton_0_4,[[].concat([this._el_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (1 === requestNodeIndex))) { return this._Icon_1_3; }
    if (((token === import23.FabButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._FabButton_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = 'facebook';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._FabButton_0_4.color = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_2:any = 'logo-facebook';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Icon_1_3.name = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._Icon_1_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_1,'hide',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_ClubPage0>this.parent)._query_FabButton_37_0.setDirty();
  }
  destroyInternal():void {
    this._Icon_1_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openLink(this.parent.context.club.club_social_links['facebook'])) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ClubPage7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubPage7(viewUtils,parentInjector,declarationEl);
}
class _View_ClubPage8 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FabButton_0_4:import23.FabButton;
  _el_1:any;
  _Icon_1_3:import24.Icon;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage8,renderType_ClubPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','twitter');
    this.renderer.setElementAttribute(this._el_0,'ion-fab','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import41.viewFactory_FabButton0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FabButton_0_4 = new import23.FabButton(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._FabButton_0_4,[],compView_0);
    this._el_1 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_1,'name','logo-twitter');
    this.renderer.setElementAttribute(this._el_1,'role','img');
    this._Icon_1_3 = new import24.Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_1),this.renderer);
    compView_0.create(this._FabButton_0_4,[[].concat([this._el_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (1 === requestNodeIndex))) { return this._Icon_1_3; }
    if (((token === import23.FabButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._FabButton_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = 'twitter';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._FabButton_0_4.color = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_2:any = 'logo-twitter';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Icon_1_3.name = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._Icon_1_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_1,'hide',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_ClubPage0>this.parent)._query_FabButton_37_0.setDirty();
  }
  destroyInternal():void {
    this._Icon_1_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openLink(this.parent.context.club.club_social_links['twitter'])) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ClubPage8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubPage8(viewUtils,parentInjector,declarationEl);
}
class _View_ClubPage9 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FabButton_0_4:import23.FabButton;
  _el_1:any;
  _Icon_1_3:import24.Icon;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage9,renderType_ClubPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','instagram');
    this.renderer.setElementAttribute(this._el_0,'ion-fab','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import41.viewFactory_FabButton0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FabButton_0_4 = new import23.FabButton(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._FabButton_0_4,[],compView_0);
    this._el_1 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_1,'name','logo-instagram');
    this.renderer.setElementAttribute(this._el_1,'role','img');
    this._Icon_1_3 = new import24.Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_1),this.renderer);
    compView_0.create(this._FabButton_0_4,[[].concat([this._el_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (1 === requestNodeIndex))) { return this._Icon_1_3; }
    if (((token === import23.FabButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._FabButton_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = 'instagram';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._FabButton_0_4.color = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_2:any = 'logo-instagram';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Icon_1_3.name = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._Icon_1_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_1,'hide',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_ClubPage0>this.parent)._query_FabButton_37_0.setDirty();
  }
  destroyInternal():void {
    this._Icon_1_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openLink(this.parent.context.club.club_social_links['instagram'])) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ClubPage9(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubPage9(viewUtils,parentInjector,declarationEl);
}
class _View_ClubPage10 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FabButton_0_4:import23.FabButton;
  _el_1:any;
  _Icon_1_3:import24.Icon;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage10,renderType_ClubPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','snapchat');
    this.renderer.setElementAttribute(this._el_0,'ion-fab','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import41.viewFactory_FabButton0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FabButton_0_4 = new import23.FabButton(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._FabButton_0_4,[],compView_0);
    this._el_1 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_1,'name','logo-snapchat');
    this.renderer.setElementAttribute(this._el_1,'role','img');
    this._Icon_1_3 = new import24.Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_1),this.renderer);
    compView_0.create(this._FabButton_0_4,[[].concat([this._el_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (1 === requestNodeIndex))) { return this._Icon_1_3; }
    if (((token === import23.FabButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._FabButton_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = 'snapchat';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._FabButton_0_4.color = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_2:any = 'logo-snapchat';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Icon_1_3.name = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._Icon_1_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_1,'hide',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_ClubPage0>this.parent)._query_FabButton_37_0.setDirty();
  }
  destroyInternal():void {
    this._Icon_1_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openLink(this.parent.context.club.club_social_links['snapchat'])) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ClubPage10(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubPage10(viewUtils,parentInjector,declarationEl);
}
class _View_ClubPage11 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FabButton_0_4:import23.FabButton;
  _el_1:any;
  _Icon_1_3:import24.Icon;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ClubPage11,renderType_ClubPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','youtube');
    this.renderer.setElementAttribute(this._el_0,'ion-fab','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import41.viewFactory_FabButton0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FabButton_0_4 = new import23.FabButton(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._FabButton_0_4,[],compView_0);
    this._el_1 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_1,'name','logo-youtube');
    this.renderer.setElementAttribute(this._el_1,'role','img');
    this._Icon_1_3 = new import24.Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_1),this.renderer);
    compView_0.create(this._FabButton_0_4,[[].concat([this._el_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (1 === requestNodeIndex))) { return this._Icon_1_3; }
    if (((token === import23.FabButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._FabButton_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = 'youtube';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._FabButton_0_4.color = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_2:any = 'logo-youtube';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Icon_1_3.name = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._Icon_1_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_1,'hide',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_ClubPage0>this.parent)._query_FabButton_37_0.setDirty();
  }
  destroyInternal():void {
    this._Icon_1_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openLink(this.parent.context.club.club_social_links['youtube'])) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ClubPage11(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClubPage11(viewUtils,parentInjector,declarationEl);
}